# Generated by Django 4.2.5 on 2023-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labotics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=15)),
                ('l_id', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('name', models.CharField(default='', max_length=100)),
                ('l_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(default='NULL', max_length=150)),
                ('popu', models.PositiveSmallIntegerField(default=0)),
                ('certi', models.CharField(default='NULL', max_length=50)),
                ('est', models.PositiveSmallIntegerField(default=2020)),
                ('latest_eq', models.PositiveSmallIntegerField(default=2020)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=15)),
                ('desc', models.CharField(default='NULL', max_length=500)),
                ('linked_test', models.TextField()),
                ('requirements', models.TextField()),
                ('min_age', models.SmallIntegerField(default=0)),
                ('purpose', models.CharField(max_length=150)),
                ('home_testing', models.BooleanField(default=False)),
            ],
        ),
    ]
