# Generated by Django 4.2.5 on 2023-09-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_labotics_l_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labotics',
            name='l_name',
        ),
    ]
